### ISSUE TITLE
Syntaxerror when using a large MA.JSON-file 

### ISSUE THREAD

**Issue by FightingBugs** [rpreiner/tam#1]
Hi,
thank you for the program, it is great. I found it, when reading the magazine ComputerGenealogie 1/2021

Problems: 
1. Problem
---------------
Syntaxerror when using a large MA.JSON-file 
The Program is working with a MA.JSON file containing about 120 people and their links.
The program is not working with a MA.JSON file for about 790 people and 1100 links.

Message at the Console:
"SyntaxError: JSON.parse: unexpected character at line 86 column 66 of the JSON data".

System: Pc, Windows 10, Browser Firefox Version 66.
Same Error with d3.v5.min.js and with d3.v6.min.js .

I think there is no error in the MA.JSON file, because the file is produced by a program and since the file with only about 120 people and produced by the same programm  is working.

I have two pictures showing the region about line 86 using an editor and using the
hex editor

2. Problem
--------------

Doubleclick on Screen without effect at d3.v6.min.js.

When using d3.v5.min.js after a double click with the left mouse key on the screen the picture is enlarged.
When using d3,v6.min.js  a double click with the left mouse key is not working, no enlargement.

**Comment by rpreiner** [comment]
Hi, thanks for your feedback!

Problem 1: 790 nodes should be processable. How did you create the altered MA.json file? If you exported them from e.g. your GEDCOM, I suspect there might be some special character in the encoding from the original file, e.g. in person names, that might mess up the JSON parser. Can you send me the pictures, or your JSON?

Problem 2: The current program was developed and tested under D3 v5. The double-click zoom is not a specific feature implemented in the TAM demo, so I suppose its an inherent D3 interaction feature, that might have been removed in D3 v6 (just an assumption)

Best,
R

**Comment by RPiDespair** [comment]
Hello FightingBugs,

You are also testing TAM on Win10.
Would you please tell me which gedcom parser you are using?

gedcom-parser
Elliotchance
Get2Json
I could already find, but I am not sure which one to use under Windows.

Many greetings
 RPiDespair

**Comment by FightingBugs** [comment]
Hi RPIDespair,
being a programmer I am using a parser of my own.
Sorry but I do not know a suited public parser.
Yours FightingBugs

**Comment by FightingBugs** [comment]
The problem with the JSON error is solved. I happened to use an editor that understood the JSON-file. It showed me the errors, some wrong formated numbers. Sorry for bothering everybody. My experience with errors reported about JSON-files: Use a syntax checker to check the JSON-file.
