### ISSUE TITLE
a blank display to the right of the controls

### ISSUE THREAD

**Issue by RPiDespair** [rpreiner/tam#2]
Hello,

I also discovered your project in the magazine Computer Genealogy 1/2021.

When I test it, I get no error message but a blank display to the right of the controls.

If I understood it correctly, I unpack the zip file into a folder on my hard disk and open the file index.htm with the browser.

Same behavior with Firefox version 86.0.1 (64-bit) and Chrome (version 89.0.4389.90 (Official Build) (64-bit)) in 
Windows 10 Pro
Version 2004
Operating system build 19041.867.

What could be the cause of this?

Many greetings
 RPiDespair

**Comment by rpreiner** [comment]
Hi!

The security settings of your browser need to allow reading local files of your client file system. To change this in Firefox, 

1. enter  "about:config"  in the address bar,
2. perhaps click a button to confirm a warning
3. search for settings flags and change them accordingly:

   privacy.file_unique_origin = false 

On older versions of Firefox, the settings to change might be:

   security.mixed.content.block_active_content = false
   security.mixed.content.block_active_display = true 

Hope that helps!

**Comment by RPiDespair** [comment]
Hello Mr. Preiner,

thank you very much for your help and the very interesting project.
privacy.file_unique_origin = false
was the solution.

With the original MA.json my old PC comes to its performance limit.
Firefox reports when building the graphic and changing the settings:
"A website slows down your browser" and the processor fan increases the speed.
Maybe now is the time to retire the PC.
Now I have to test it once with my data. Some JSON parsers like 
gedcom-parser
Elliotchance
Get2Json
I could already find, but I am not sure which one to use under Windows.

Many greetings
 RPiDespair

**Comment by rpreiner** [comment]
Note that a recent update allows to load GEDCOMs directly.

Yes, unfortunately, performance of DOM-based graph updates limits the size of graphs in this demo. Future updates still might bring performance and efficiency improvements.

Best, 
R
