### ISSUE TITLE
Which GEDCOM to JSON converter was used?

### ISSUE THREAD

**Issue by FlominatorTM** [rpreiner/tam#3]
Hi, great project you have there!

Which tool do you recommend to generate the JSON file from a GEDCOM file?

Kind regards
Flo

**Comment by rpreiner** [comment]
Hi!
I can't recommend a particular one at the moment, but due to the increased interest, I plan to update the demo version here to include a GEDCOM loader in the next few days.
Best,
R

**Comment by FlominatorTM** [comment]
Hi! 
I couldn't help myself, forked your repository and wrote a converter:
https://github.com/FlominatorTM/tam

Kind regards
Flo

**Comment by rpreiner** [comment]
Thanks for the heads-up! 
I added my complementary GEDCOM importer (+ birth date estimation) in the recent update as well.

Best,
R
